### ISSUE TITLE
Turn sequelize hook an installable

### ISSUE THREAD

**Issue by cesardeazevedo** [cesardeazevedo/sails-hook-sequelize-blueprints#1]
[https://github.com/cesardeazevedo/sails-hook-sequelize-blueprints/tree/master/test/fixtures/sampleapp/api/hooks](https://github.com/cesardeazevedo/sails-hook-sequelize-blueprints/tree/master/test/fixtures/sampleapp/api/hooks)

**Comment by festo** [comment]
I do my best, I hope I don't screw anything, because this is my first package. :smile: 
[sails-hook-sequelize](https://github.com/festo/sails-hook-sequelize)

**Comment by cesardeazevedo** [comment]
perfect, i'll take a look and add to the sampleapp test.

thank you very much.
