### ISSUE TITLE
Selective populate not working

### ISSUE THREAD

**Issue by NetoBraghetto** [cesardeazevedo/sails-hook-sequelize-blueprints#16]
i am trying to use the param populate
eg: /resource?populate=reso1,reso2,reso3

but its no working

**Comment by cesardeazevedo** [comment]
I've just implement it, can you try again at 0.1.2?

let me know if you got it.

**Comment by NetoBraghetto** [comment]
Hum.. not yey
got this

```
Error: Only HasMany associations support include.separate
at validateIncludedElement (/home/neto/nodewww/sails-api/node_modules/sequelize/lib/model.js:631:11)
```

I can post my models here, if it helps

**Comment by NetoBraghetto** [comment]
Found the problem...
Your file "/actionsUtil.js" is generating associations like this
`{ model: ModelName, as: 'name', limit: 15 }`
i forced an object WHITOUT limit and it worked.. seems to be a Sequelize bug

Will try a pull request later =)

**Comment by cesardeazevedo** [comment]
you have to specify the alias `as`, take a look at these models.

https://github.com/cesardeazevedo/sails-hook-sequelize-blueprints/blob/master/test/fixtures/sampleapp/api/models/user.js

https://github.com/cesardeazevedo/sails-hook-sequelize-blueprints/blob/master/test/fixtures/sampleapp/api/models/image.js

**Comment by NetoBraghetto** [comment]
I used your models and its not working...
Look at mines

```
// Product Model

module.exports = {
    options: {
        freezeTableName: true,
        tableName: 'products',
        underscored: true
    },
    attributes: {
        id: {
            type: Sequelize.INTEGER.UNSIGNED,
            primaryKey: true,
            autoIncrement: true
        },
        ...
    },
    associations: function () {
        Products.belongsTo(Brands, {
            as: 'brand',
            foreignKey: {
                name: 'brand_id',
                allowNull: false
            }
        });
    }
};


// Brand Model

module.exports = {
    options: {
        freezeTableName: false,
        tableName: 'brands',
        underscored: true
    },
    attributes: {
        id: {
            type: Sequelize.INTEGER.UNSIGNED,
            primaryKey: true,
            autoIncrement: true
        },
        ...
    },
    associations: function () {
        Brands.hasMany(Products, {
            as: 'products',
            onDelete: 'RESTRICT',
            foreignKey: {
                allowNull: false
            }
        });
    }
};
```

**Comment by NetoBraghetto** [comment]
look what i found
https://github.com/sequelize/sequelize/issues/1897

**Comment by cesardeazevedo** [comment]
I got it, it happens when you trying to limit a belongsTo association, in this case, will occur's on /product?populate=[brand], and didn't happens when you try /brand?populate=[product], I gonna fix that.

**Comment by NetoBraghetto** [comment]
`/brands?populate=[]`
Returns all associations

`/brands?populate=Products`
everything good =)

**Comment by cesardeazevedo** [comment]
I fixed, can you try `product?populate=brand` at `v0.1.3`?

**Comment by NetoBraghetto** [comment]
Yep working =)
